import os
import time
import hashlib
import re
from openai import OpenAI

# --- 1. 配置 DeepSeek ---
api_key = os.environ.get("DEEPSEEK_API_KEY")
if not api_key:
    print("⚠️  DEEPSEEK_API_KEY not found in environment variables.")
    print("Skipping translation sync.")
    print("Please set the DEEPSEEK_API_KEY environment variable to enable this feature.")
    print("If you're running this locally, don't worry—your GitHub Actions workflow will still perform translations automatically if DEEPSEEK_API_KEY is set there.")
    # Exit gracefully so the deploy script continues
    exit(0)

client = OpenAI(
    api_key=api_key, # 从环境变量读取
    base_url="https://api.deepseek.com"         # 国内服务器地址
)

# 自动生成文件的标记 (放在文件末尾，避免破坏 YAML 头)
AUTO_MARKER = "\n\n<!-- Auto-generated by DeepSeek. DO NOT EDIT. -->\n"

# --- 2. 辅助函数 ---

def calculate_hash(content):
    """计算字符串内容的 MD5 哈希值"""
    return hashlib.md5(content.encode('utf-8')).hexdigest()

def get_source_hash_from_file(filepath):
    """从目标文件中提取记录的源文件 Hash 值"""
    if not os.path.exists(filepath):
        return None
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            # 查找最后一行是否包含 Hash 标记
            # 格式: <!-- Source Hash: xxxxx -->
            if "<!-- Source Hash:" in content:
                parts = content.split("<!-- Source Hash:")
                if len(parts) > 1:
                    return parts[-1].strip().replace("-->", "").strip()
    except Exception:
        return None
    return None

# --- 3. 提示词工程 (Prompt Engineering) ---
def get_prompt(target_lang, is_first_chunk=True):
    lang = "English" if target_lang == "en" else "Chinese"
    
    base_prompt = f"""
You are an expert academic translator. 
TASK: Translate the following Quarto Markdown (.qmd) content to {lang}.

CORE OBJECTIVES:
1. ACCURACY: Maintain original meaning, tone, and academic rigor.
2. RENDERABILITY: Output valid Markdown. Preserve syntax, structure, and special markers.
"""

    yaml_rules = f"""
【YAML FRONTMATTER RULES】:
1. The file starts with a YAML block (between ---).
2. TRANSLATE 'title' and 'description' values.
3. DO NOT translate other keys.
4. CHANGE 'lang' value to '{target_lang}'.
5. PRESERVE structure.
"""

    content_rules = """
【CONTENT RULES】:
1. DO NOT translate code blocks (```...```).
2. DO NOT translate inline code (`...`) unless it is a prose description.
3. DO NOT translate LaTeX ($...$).
4. DO NOT translate citations/cross-refs.
5. DO NOT translate file paths.
6. Output ONLY the translated content.
"""

    if is_first_chunk:
        return base_prompt + yaml_rules + content_rules
    else:
        return base_prompt + content_rules + "\nNOTE: This is a continuation chunk. DO NOT add YAML frontmatter. Start translating directly."

def split_markdown_smartly(text, max_chars=3000):
    """
    智能切分 Markdown，优先保证代码块完整，优先在标题处切分。
    防止标题孤儿 (Orphaned Header)。
    """
    lines = text.split('\n')
    chunks = []
    current_chunk = []
    current_length = 0
    
    in_code_block = False
    last_line_was_header = False # 核心标志位：上一行是标题吗？
    
    for line in lines:
        # 1. 维护代码块状态 (```)
        if line.strip().startswith('```'):
            in_code_block = not in_code_block
        
        line_len = len(line) + 1
        
        # 2. 识别是否是标题 (支持 #, ##, ###...)
        # 注意：只在非代码块内识别
        is_header = (not in_code_block) and re.match(r'^#{1,6}\s', line)
        
        # 3. 决策：是否切分？
        should_split = False
        
        if not in_code_block:
            # 策略 A: 遇到新标题，且当前块已经足够大了 (比如 > 50% max_chars)
            # 这样标题就会成为【新块的第一行】，非常完美。
            if is_header and current_length > (max_chars * 0.5):
                should_split = True
            
            # 策略 B: 遇到段落空行，且当前块严重超长 (强制切分)
            # 关键修正：如果上一行是标题，绝对不切！防止标题变成上一块的“孤儿”。
            elif (current_length > max_chars) and (line.strip() == ""):
                if not last_line_was_header: 
                    should_split = True

        # 4. 执行切分
        if should_split:
            chunks.append('\n'.join(current_chunk))
            current_chunk = []
            current_length = 0
            # 重置状态，因为新块开始了，肯定不是“上一行是标题”的尴尬状态
            last_line_was_header = False 
        
        # 5. 加入当前行
        current_chunk.append(line)
        current_length += line_len
        
        # 6. 更新状态，供下一轮循环判断使用
        if is_header:
            last_line_was_header = True
        elif line.strip() != "": 
            # 只有遇到非空行，才解除“刚写完标题”的状态
            # 这样可以允许标题后跟一个空行，然后再跟正文
            last_line_was_header = False
            
    # 处理最后一块
    if current_chunk:
        chunks.append('\n'.join(current_chunk))
        
    return chunks

# --- 3. 核心逻辑 ---
def translate_chunk(text, system_prompt):
    for i in range(3): # 失败重试 3 次
        try:
            response = client.chat.completions.create(
                model="deepseek-chat",
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": text}
                ],
                temperature=0.1,
                stream=False
            )
            return response.choices[0].message.content
        except Exception as e:
            print(f"    [API Error] Attempt {i+1}: {e}")
            time.sleep(2)
    return None

def translate_text(text, target_lang):
    # 1. 智能切分，阈值设为 3500 字符
    chunks = split_markdown_smartly(text, max_chars=3500)
    
    # 如果只有一段，直接翻译，不加上下文逻辑
    if len(chunks) == 1:
        sys_prompt = get_prompt(target_lang, is_first_chunk=True)
        return translate_chunk(chunks[0], sys_prompt)

    print(f"    [INFO] File is long ({len(text)} chars). Splitting into {len(chunks)} chunks...")
    translated_chunks = []
    last_chunk_tail = "" # 用于保存上一段的末尾
    
    for idx, chunk in enumerate(chunks):
        print(f"    ...Translating chunk {idx+1}/{len(chunks)} ({len(chunk)} chars)...")
        
        is_first = (idx == 0)
        
        # 2. 生成带上下文的 Prompt
        sys_prompt = get_prompt(target_lang, is_first_chunk=is_first)
        
        # 如果不是第一段，注入上下文
        if not is_first and last_chunk_tail:
            sys_prompt += f"\n\n[CONTEXT]: The text above connects to the following translation history:\n...{last_chunk_tail}\n\nMaintain consistent terminology."

        # 3. 调用 API
        translated_part = translate_chunk(chunk, sys_prompt)
        
        if not translated_part:
            print(f"    [ERR] Failed to translate chunk {idx+1}")
            return None # 只要有一段失败，整体就失败，防止文件残缺
            
        translated_chunks.append(translated_part)
        
        # 4. 更新上下文 (取这段译文的后 800 个字符)
        last_chunk_tail = translated_part[-800:]
        
    return "\n\n".join(translated_chunks)

def is_auto_generated(filepath):
    """检查文件是否是 AI 生成的"""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            return "Auto-generated by DeepSeek" in content
    except:
        return False

def sync_folder(source_root, target_root, target_lang_code):
    """同步整个文件夹"""
    for root, _, files in os.walk(source_root):
        for file in files:
            if not file.endswith(".qmd"):
                continue
            
            src_path = os.path.join(root, file)
            
            # 计算相对路径，保持目录结构
            rel_path = os.path.relpath(src_path, source_root)
            dest_path = os.path.join(target_root, rel_path)
            
            # 跳过 content/zh/index.qmd 或 content/en/index.qmd (语言根目录的首页)
            # 因为它们是由根目录的 index.qmd 生成的，不应该作为源文件再去翻译
            # 使用 abspath 比较，确保只跳过根层级的 index.qmd，不跳过 blog/index.qmd
            if file == "index.qmd" and os.path.abspath(root) == os.path.abspath(source_root):
                 print(f"  [SKIP] Skipping generated language root index: {src_path}")
                 continue

            sync_single_file(src_path, dest_path, target_lang_code)

def post_process_root_index(content, target_lang):
    """
    Adjust paths when moving from Root index.qmd to content/{lang}/index.qmd
    """
    # 1. Adjust assets path (Root -> Subfolder means depth +2)
    # Handle various formats: assets/, "assets/, ./assets/, "
    replacements = [
        ('image: assets/', 'image: ../../assets/'),
        ('image: "assets/', 'image: "../../assets/'),
        ('image: ./assets/', 'image: ../../assets/'),
        ('href: assets/', 'href: ../../assets/'),
        ('href: "assets/', 'href: "../../assets/'),
        ('src="assets/', 'src="../../assets/'),
        ('](assets/', '](../../assets/'),
        ('](./assets/', '](../../assets/')
    ]
    
    for old, new in replacements:
        content = content.replace(old, new)
    
    # 2. Adjust content links
    src_lang = "zh" if target_lang == "en" else "en"
    
    # Switch language in paths
    content = content.replace(f'content/{src_lang}/', f'content/{target_lang}/')
    
    # Remove prefix to make it relative (since we are now IN content/{target_lang}/)
    # FIX: Do not replace globally, only in link/attribute contexts
    prefix = f'content/{target_lang}/'
    
    # Markdown links: [text](content/en/path) -> [text](path)
    content = content.replace(f']({prefix}', '](')
    
    # HTML/YAML attributes
    content = content.replace(f'href: {prefix}', 'href: ')
    content = content.replace(f'href="{prefix}', 'href="')
    content = content.replace(f'src="{prefix}', 'src="')
    content = content.replace(f'image: {prefix}', 'image: ')
    content = content.replace(f'contents: {prefix}', 'contents: ')
    content = content.replace(f'contents: "{prefix}', 'contents: "')
    
    return content

def sync_single_file(src_path, dest_path, target_lang_code, is_root_index=False):
    """同步单个文件，使用 Hash 校验"""
    if not os.path.exists(src_path):
        return

    # 如果源文件是 AI 生成的，跳过（防止循环翻译）
    if is_auto_generated(src_path):
        print(f"  [SKIP] Source is auto-generated: {src_path}")
        return

    # 读取源文件内容
    with open(src_path, 'r', encoding='utf-8') as f:
        src_content = f.read()
    
    # 计算源文件 Hash
    current_hash = calculate_hash(src_content)
    
    # 检查目标文件是否需要更新
    should_translate = False
    if not os.path.exists(dest_path):
        should_translate = True
    else:
        # 检查是否是 AI 生成的（防止覆盖用户手动修改）
        if not is_auto_generated(dest_path):
            print(f"  [SKIP] Target exists and is NOT auto-generated: {dest_path}")
            return
        
        # 对比 Hash
        recorded_hash = get_source_hash_from_file(dest_path)
        if recorded_hash != current_hash:
            should_translate = True
        else:
            print(f"  [SKIP] Up-to-date (Hash match): {dest_path}")
            return

    if should_translate:
        print(f"Translating {src_path} -> {target_lang_code.upper()}...")
        translated = translate_text(src_content, target_lang_code)
        
        if translated:
            # 如果是首页，进行路径修正
            if is_root_index:
                translated = post_process_root_index(translated, target_lang_code)
            
            # 构造最终内容：翻译内容 + 自动标记 + Hash 标记
            hash_marker = f"<!-- Source Hash: {current_hash} -->"
            final_content = translated + AUTO_MARKER + hash_marker
            
            os.makedirs(os.path.dirname(dest_path), exist_ok=True)
            with open(dest_path, 'w', encoding='utf-8') as f:
                f.write(final_content)
            print(f"  [OK] Saved: {dest_path}")
        else:
            print(f"  [ERR] Translation failed for: {src_path}")
    else:
        # Optional: print skipped files to show progress
        pass


def detect_language(filepath):
    """读取文件的 YAML 头来检测语言 (lang: en/zh)"""
    try:
        with open(filepath, 'r', encoding='utf-8') as f:
            # 读取前 50 行，通常 YAML 头就在这里
            head = []
            for _ in range(50):
                line = f.readline()
                if not line: break
                head.append(line)
        
        in_yaml = False
        for line in head:
            line = line.strip()
            if line == "---":
                if in_yaml: break # 结束 YAML
                in_yaml = True
                continue
            if in_yaml and line.startswith("lang:"):
                lang_val = line.split(":", 1)[1].strip().lower()
                if "zh" in lang_val: return "zh"
                if "en" in lang_val: return "en"
    except:
        pass
    return None # 无法检测

if __name__ == "__main__":
    # 强制切换到项目根目录 (即脚本所在目录的上一级)，确保能找到 index.qmd
    os.chdir(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

    print("--- Starting DeepSeek Sync ---")
    # 中 -> 英
    print("Syncing Chinese to English...")
    sync_folder("content/zh", "content/en", "en")
    # 英 -> 中
    print("Syncing English to Chinese...")
    sync_folder("content/en", "content/zh", "zh")

    # ============================================================
    # 智能首页同步逻辑
    # ============================================================
    root_index = "index.qmd"
    if os.path.exists(root_index):
        root_lang = detect_language(root_index)
        
        # 情况 A: 根目录是中文 (默认情况)
        if root_lang == "zh":
            print(f"Detected Root Index as CHINESE. Syncing to English...")
            sync_single_file(root_index, "content/en/index.qmd", "en", is_root_index=True)
            
        # 情况 B: 根目录是英文 (想要首页更国际化的使用者)
        elif root_lang == "en":
            print(f"Detected Root Index as ENGLISH. Syncing to Chinese...")
            sync_single_file(root_index, "content/zh/index.qmd", "zh", is_root_index=True)
            
        # 情况 C: 没写 lang
        else:
            print("❌ ERROR: No 'lang' field found in the ROOT 'index.qmd' YAML frontmatter!")
            print("   The script cannot determine the source language of the homepage.")
            print("   ACTION REQUIRED: Please add 'lang: en' or 'lang: zh' to the YAML header of the 'index.qmd' file in the project root.")
            print("   Skipping homepage translation for now.")
            # 不执行 sync_single_file，直接跳过

    print("--- End ---")